name: CD - Azure Static Web Apps

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  cd:
    uses: emilgruzalski/gh-reusable-workflows/.github/workflows/cd-az-stapp.yml@v1
    with:
      app-location: '/'            # Replace with your app source code path
      api-location: 'api'          # Replace with your API source code path
      app-artifact-location: 'build'  # Replace with your build output path
    secrets:
      azure-static-web-apps-api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      gh-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
