name: CI - Java

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: emilgruzalski/gh-reusable-workflows/.github/workflows/ci-java.yml@v1
    with:
      image-name: 'my-java-app'  # Replace with your app name
      java-version: '21'
      working-directory: '.'
      dockerfile: './Dockerfile'
      context: '.'
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      packages: write
