name: Generate SBOM
description: Generates a Software Bill of Materials for a container image and uploads it as an artifact

inputs:
  image:
    description: Full container image reference (e.g., ghcr.io/owner/image:tag)
    required: true
  github-token:
    description: GitHub token for ghcr.io authentication
    required: true
  format:
    description: SBOM output format (spdx-json, cyclonedx-json)
    required: false
    default: "spdx-json"
  artifact-name:
    description: Name for the uploaded SBOM artifact
    required: false
    default: "sbom"
  dependency-snapshot:
    description: Whether to submit SBOM to GitHub Dependency Submission API
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: ${{ inputs.image }}
        format: ${{ inputs.format }}
        artifact-name: ${{ inputs.artifact-name }}
        dependency-snapshot: ${{ inputs.dependency-snapshot }}
