name: Node code quality
description: Runs lint, tests, and build for Node.js projects using Bun

inputs:
  node-version-file:
    description: Node.js version file
    required: false
    default: "package.json"
  working-directory:
    description: Working directory
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bun install --frozen-lockfile

    - name: Lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bun run lint

    - name: Test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bun test

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bun run build
