name: Go code quality
description: Runs linting and tests for Go projects

inputs:
  go-version-file:
    description: Go version file
    required: false
    default: "go.mod"
  working-directory:
    description: Working directory
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod download

    - name: Vet
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go vet ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go test -race -coverprofile=coverage.out ./...
