name: Deploy web app to Azure Static Web Apps

on:
  workflow_call:
    inputs:
      app-location:
        required: false
        type: string
        default: "/"
      api-location:
        required: false
        type: string
        default: "api"
      app-artifact-location:
        required: false
        type: string
        default: "build"
    secrets:
      azure-static-web-apps-api-token:
        required: true
      gh-token:
        required: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: Build and Deploy Job
    permissions:
      contents: read           # For checking out code
      pull-requests: write     # For commenting on PRs with deployment URLs
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9 # v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.azure-static-web-apps-api-token }}
          repo_token: ${{ secrets.gh-token }}
          action: "upload"
          app_location: ${{ inputs.app-location }}
          api_location: ${{ inputs.api-location }}
          app_artifact_location: ${{ inputs.app-artifact-location }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Close Pull Request Job
    permissions:
      pull-requests: write     # For updating PR status
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9 # v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.azure-static-web-apps-api-token }}
          action: "close"
          app_location: ${{ inputs.app-location }}
